GET http://localhost:8080/event/1

### Sample Success Response (200)
# {
#   "data": {
#     "ID": 1,
#     "Name": "Go Workshop Jakarta",
#     "Description": "A beginner-friendly workshop covering Go fundamentals and best practices.",
#     "Location": "Jakarta",
#     "DateTime": "2025-12-16T09:00:00+07:00",
#     "UserID": 1
#   },
#   "message": "Successfully get event details"
# }