DELETE http://localhost:8080/event/1/unregister
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbmVkb2VAZXhhbXBsZS5jb20iLCJleHAiOjE3NjY1NDg1NzMsInVzZXJJZCI6Mn0.z6nzGpVmhQNeVVLiSkFxGyzjgeVGEEMN8-W88XylzhE

### Sample Success Response (200)
# {
#   "message": "Sucessfully unregister event"
# }